version: '3.8'
services:
  rabbitmq:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: HWrabbit
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    hostname: rabbitmq
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: haap
      RABBITMQ_DEFAULT_PASS: microservices
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host
volumes:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge